# Site settings
title: Wasteland
name: Wasteland # your name
email: ryont@gmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryont.github.io" # the base hostname & protocol for your site
twitter_username:  # your Twitter username
github_username: ryont # your Github username
_username: amber_han # your disqus username

google-analytics:  # add it if you have one

skillstree: off # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
